server:
  port: 8080
spring:
  application:
    name: lucky-apiserver
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lucky-star
    username: root
    password: yue199625
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
wechat:
  appid: wx293938d12189809d
  secret: ccac88ef2c23584f488dc0ddd5b13d02
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
  phoneNumberUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token=ACCESS_TOKEN
  code2SessionUrl: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
huawei:
  endpoint: obs.cn-east-3.myhuaweicloud.com
  ak: HPUASOL8WDLFLFNDMI6K
  sk: MYjO9I9W26wEExH0XHv5TwXSMAbJYIym73s7pK53
  bucketname: lucky-wxcd
  BASEURL1: https://lucky-wxcd.obs.cn-east-3.myhuaweicloud.com/
wx:
  pay:
    appid:
    mchserialno:
    appsecret:
    apikey:
    notifyurl: "/wechat/pay/callback"
    keypath:
    notifyhost:

